### ISSUE TITLE
[machine learning] create a jupyter notebook for the algorithm prototype 

### ISSUE THREAD

**Issue by greatday4april** [greatday4april/what-to-eat-ml-backend#13]
recommend restaurants based on similarity.

input: 5 - 10 favorite restaurants; menu from all nearby retaurants

use the favorites as the pool
train a model based on restaurant similarity 

output: pick one from the pool and output its similar restaurant

bonus: have functionality that you can like / dislike using streamlit 
- https://towardsdatascience.com/how-to-build-a-simple-machine-learning-web-app-in-python-68a45a0e0291

**Comment by 24451yolanda** [comment]
Completed recommender based on menu content similarity.

Training data using Tomato API free calls

Model is trained based on menu similarity, then output 5 other most similar places as recommendations 

To be Done: bonus: have functionality that you can like / dislike using streamlit
