### ISSUE TITLE
popup category filter

### ISSUE THREAD

**Issue by greatday4april** [greatday4april/what-to-eat-ml-backend#19]
- top right corner should have a filter button
- popup dialog with semi-transparent background
- with a few tags (categories)  (there's already a `<Tags` component)

**Comment by fish518518** [comment]
<img width="384" alt="Screen Shot 2020-08-15 at 4 29 14 PM" src="https://user-images.githubusercontent.com/26806177/90323320-88760f80-df14-11ea-84cf-18b604291c6b.png">
