### ISSUE TITLE
[backend] research on restaurant apis

### ISSUE THREAD

**Issue by greatday4april** [greatday4april/what-to-eat-ml-backend#3]
- we could use yelp api to find restaurants, but they are the not the best one to analyze similarity
- to do content-based filtering ML, we should find apis help us find similar restaurant given one. 
https://openmenu.com/api/docs/restaurant.php seems like a good start because we can determine similarity between two restaurants based on their menus
- find good apis and create a postman collections that works and share. (https://www.toolsqa.com/postman/collections-in-postman/)
- we also want to understand restrictions of using these apis, like how long we can keep the data etc.

**Comment by kuanghsuan** [comment]
https://usmenuapi.appspot.com/docs

**Comment by greatday4april** [comment]
we will use yelp for photos and us restaurant menu api for menu
