### ISSUE TITLE
[Mobile] Research on swiping UI libraries

### ISSUE THREAD

**Issue by greatday4april** [greatday4april/what-to-eat-ml-backend#5]
Find similar mobile open source libraries or UI kits that 1. works smoothly 2. looks appealing

## reference
- https://github.com/stevenpersia/tinder-react-native 
  - design: https://dribbble.com/shots/5631075-Dating-App-Sketch-Freebie-Day-334-365-Project365

**Comment by fish518518** [comment]
**Effect Demo：https://pub.dev/packages/flutter_swiper#build-in-layouts**
**flutter_swiper Installation**
1. Depend on it
Add this to your package’s pubspec.yaml file:
`dependencies: flutter_swiper: ^1.1.6`
2. Install it
You can install packages from the command line:
`flutter pub get`
3. Restart your IDE
4. Import it
Now in your Dart code, you can use:
`import 'package:flutter_swiper/flutter_swiper.dart';`
5. Sample code
```
import 'package:flutter/material.dart';
import 'package:flutter_swiper/flutter_swiper.dart';
void main() => runApp(new MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body:  new Swiper(
        itemBuilder: (BuildContext context,int index){
          return new Image.network("http://via.placeholder.com/350x150",fit: BoxFit.fill,);
        },
        itemCount: 3,
        pagination: new SwiperPagination(),
        control: new SwiperControl(),
      ),
    );
  }
}
```

**Comment by fish518518** [comment]
How about this one? 
https://blog.geekyants.com/tinder-swipe-in-flutter-7e4fc56021bc
